preload = /home/kyri/Pictures/Wallpapers/athens.webp
preload = /home/kyri/Pictures/Wallpapers/futuristic-athens.webp
preload = /home/kyri/Pictures/Wallpapers/futuristic.webp
wallpaper = HDMI-A-2,/home/kyri/Pictures/Wallpapers/athens.webp

ipc = on
splash = true
interval=300
mode=fill

