animations {
    enabled = true
    bezier = dreamIn, 0.0, 0.85, 0.0, 1.0
    bezier = linear, 0.0, 0.0, 1.0, 1.0

    animation = windows, 1, 14, dreamIn, slide
    animation = windowsOut, 1, 10, dreamIn, slide
    animation = windowsMove, 1, 12, dreamIn, slide
    animation = border, 1, 15, linear
    animation = fade, 1, 10, dreamIn
    animation = fadeIn, 1, 10, dreamIn
    animation = fadeOut, 1, 10, dreamIn
    animation = fadeSwitch, 1, 12, dreamIn
    animation = fadeDim, 1, 12, dreamIn
    animation = fadeShadow, 1, 8, dreamIn
    animation = workspaces, 1, 14, dreamIn, slidevert
    animation = specialWorkspace, 1, 14, dreamIn, slidevert
    animation = layers, 1, 10, dreamIn, fade
    animation = borderangle, 1, 15, linear, loop
}
