

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP  # DBus Environment
exec-once = systemctl --user start xdg-desktop-portal xdg-desktop-portal-hyprland  # XDG Portals
exec-once = waybar  # Status Bar
exec-once = hyprpaper  # Wallpaper
exec-once = swaync  # Notification Center
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1  # Polkit Agent
exec-once = ~/.config/hypr/scripts/gtk.sh  # GTK Theme
# exec-once = hyprpm reload -n  # Plugins (hyprpm)
# exec-once = xrdb -merge ~/.Xresources  # X Resources
exec-once = /home/kyri/.config/hypr/wallpaper.sh  # Wallpaper
